# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.cache/wt [current_project]
set_property parent.project_path C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/interface/axi4_if.sv
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/axi4_slave.sv
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/interface/gpio_if.sv
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/red_pitaya_dfilt1.sv
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/red_pitaya_pll.sv
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/prj/classic/rtl/red_pitaya_ps.sv
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/classic/red_pitaya_pwm.sv
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/interface/sys_bus_if.sv
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/sys_bus_interconnect.sv
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/sys_bus_stub.sv
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/prj/classic/rtl/red_pitaya_top.sv
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/acq.sv
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/evn_pkg.sv
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/asg.sv
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/asg_bst.sv
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/asg_per.sv
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/axi4_stream_cnt.sv
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/axi4_stream_demux.sv
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/axi4_stream_dly.sv
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/interface/axi4_stream_if.sv
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/axi4_stream_mux.sv
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/axi4_stream_pas.sv
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/axi4_stream_reg.sv
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/bin_and.sv
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/clb.sv
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/clkdiv.sv
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/ctrg.sv
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/cts.sv
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/debounce.sv
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/gen.sv
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/id.sv
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/la.sv
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/la_trg.sv
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/lg.sv
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/lin_add.sv
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/lin_mul.sv
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/mgmt.sv
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/muxctl.sv
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/old_acq.sv
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/old_asg.sv
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/old_asg_top.sv
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/old_id.sv
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/old_la_top.sv
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/osc.sv
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/osc_trg.sv
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/pdm.sv
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/pid.sv
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/pid_block.sv
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/pwm.sv
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/rle.sv
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/scope_dec_avg.sv
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/scope_filter.sv
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/str2mm.sv
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/str_dec.sv
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/sys_reg_array_o.sv
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/interface/axi4_lite_if.sv
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/interface/spi_if.sv
}
read_verilog -library xil_defaultlib {
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/classic/axi_wr_fifo.v
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/classic/red_pitaya_ams.v
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/classic/red_pitaya_asg.v
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/classic/red_pitaya_asg_ch.v
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/classic/red_pitaya_id.v
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/classic/red_pitaya_pid.v
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/classic/red_pitaya_pid_block.v
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/classic/red_pitaya_scope.v
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/axi4_lite_slave.v
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/classic/axi_master.v
  C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/imports/fpga/rtl/classic/red_pitaya_hk.v
}
read_ip -quiet C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/ip/mult_gen_0/mult_gen_0.xci
set_property is_locked true [get_files C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/ip/mult_gen_0/mult_gen_0.xci]

add_files C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all c:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/bd/system/ip/system_axi_protocol_converter_0_0/system_axi_protocol_converter_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/bd/system/ip/system_proc_sys_reset_0/system_proc_sys_reset_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/bd/system/ip/system_proc_sys_reset_0/system_proc_sys_reset_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/bd/system/ip/system_proc_sys_reset_0/system_proc_sys_reset_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/bd/system/ip/system_processing_system7_0/system_processing_system7_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/bd/system/ip/system_xadc_0/system_xadc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/bd/system/ip/system_xadc_0/system_xadc_0.xdc]
set_property used_in_implementation false [get_files -all C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/bd/system/system_ooc.xdc]
set_property is_locked true [get_files C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/bd/system/system.bd]

read_ip -quiet C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/ip/mult_1_2/mult_1.xci
set_property is_locked true [get_files C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/ip/mult_1_2/mult_1.xci]

read_ip -quiet C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/ip/mult_gen_1/mult_gen_1.xci
set_property is_locked true [get_files C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/ip/mult_gen_1/mult_gen_1.xci]

read_ip -quiet C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/ip/adder/adder.xci
set_property is_locked true [get_files C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/ip/adder/adder.xci]

read_ip -quiet C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/ip/adder2/adder2.xci
set_property is_locked true [get_files C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/ip/adder2/adder2.xci]

read_ip -quiet C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/ip/divider/divider.xci
set_property is_locked true [get_files C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/ip/divider/divider.xci]

read_ip -quiet C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/ip/subtractor/subtractor.xci
set_property is_locked true [get_files C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/ip/subtractor/subtractor.xci]

read_ip -quiet C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/ip/multiplier/multiplier.xci
set_property is_locked true [get_files C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/ip/multiplier/multiplier.xci]

read_ip -quiet C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/ip/divider2/divider2.xci
set_property is_locked true [get_files C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/ip/divider2/divider2.xci]

read_ip -quiet C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/ip/subtractor2/subtractor2.xci
set_property is_locked true [get_files C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/ip/subtractor2/subtractor2.xci]

read_ip -quiet C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/ip/multiplier2/multiplier2.xci
set_property is_locked true [get_files C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/ip/multiplier2/multiplier2.xci]

read_ip -quiet C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/ip/divider3/divider3.xci
set_property is_locked true [get_files C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/ip/divider3/divider3.xci]

read_ip -quiet C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/ip/adder3/adder3.xci
set_property is_locked true [get_files C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/sources_1/ip/adder3/adder3.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/constrs_1/imports/sdc/red_pitaya.xdc
set_property used_in_implementation false [get_files C:/Users/adam/Documents/Quantaser_RP_FPGA/FOG_Klaman/project_tt.srcs/constrs_1/imports/sdc/red_pitaya.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top red_pitaya_top -part xc7z010clg400-1


write_checkpoint -force -noxdef red_pitaya_top.dcp

catch { report_utilization -file red_pitaya_top_utilization_synth.rpt -pb red_pitaya_top_utilization_synth.pb }
