# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/kal.xdc

# IP: ip/adder3/adder3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder3 || ORIG_REF_NAME==adder3}]

# IP: ip/divider3/divider3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==divider3 || ORIG_REF_NAME==divider3}]

# IP: ip/multiplier2/multiplier2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==multiplier2 || ORIG_REF_NAME==multiplier2}]

# IP: ip/subtractor2/subtractor2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==subtractor2 || ORIG_REF_NAME==subtractor2}]

# IP: ip/divider2/divider2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==divider2 || ORIG_REF_NAME==divider2}]

# IP: ip/multipler/multipler.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==multipler || ORIG_REF_NAME==multipler}]

# IP: ip/subtractor/subtractor.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==subtractor || ORIG_REF_NAME==subtractor}]

# IP: ip/divider/divider.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==divider || ORIG_REF_NAME==divider}]

# IP: ip/adder2/adder2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder2 || ORIG_REF_NAME==adder2}]

# IP: ip/adder/adder.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder || ORIG_REF_NAME==adder}]
