# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/adam/Documents/Quantaser_RP_FPGA/kalman_sim/kalman_sim.cache/wt [current_project]
set_property parent.project_path C:/Users/adam/Documents/Quantaser_RP_FPGA/kalman_sim/kalman_sim.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/adam/Documents/Quantaser_RP_FPGA/kalman_sim/kalman_sim.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv C:/Users/adam/Documents/Quantaser_RP_FPGA/kalman_sim/kalman_sim.srcs/sources_1/new/red_pitaya_pll.sv
read_verilog -library xil_defaultlib C:/Users/adam/Documents/Quantaser_RP_FPGA/kalman_sim/kalman_sim.srcs/sources_1/new/kalman.v
read_ip -quiet C:/Users/adam/Documents/Quantaser_RP_FPGA/kalman_sim/kalman_sim.srcs/sources_1/ip/adder3/adder3.xci
set_property is_locked true [get_files C:/Users/adam/Documents/Quantaser_RP_FPGA/kalman_sim/kalman_sim.srcs/sources_1/ip/adder3/adder3.xci]

read_ip -quiet C:/Users/adam/Documents/Quantaser_RP_FPGA/kalman_sim/kalman_sim.srcs/sources_1/ip/divider3/divider3.xci
set_property is_locked true [get_files C:/Users/adam/Documents/Quantaser_RP_FPGA/kalman_sim/kalman_sim.srcs/sources_1/ip/divider3/divider3.xci]

read_ip -quiet C:/Users/adam/Documents/Quantaser_RP_FPGA/kalman_sim/kalman_sim.srcs/sources_1/ip/multiplier2/multiplier2.xci
set_property is_locked true [get_files C:/Users/adam/Documents/Quantaser_RP_FPGA/kalman_sim/kalman_sim.srcs/sources_1/ip/multiplier2/multiplier2.xci]

read_ip -quiet C:/Users/adam/Documents/Quantaser_RP_FPGA/kalman_sim/kalman_sim.srcs/sources_1/ip/subtractor2/subtractor2.xci
set_property is_locked true [get_files C:/Users/adam/Documents/Quantaser_RP_FPGA/kalman_sim/kalman_sim.srcs/sources_1/ip/subtractor2/subtractor2.xci]

read_ip -quiet C:/Users/adam/Documents/Quantaser_RP_FPGA/kalman_sim/kalman_sim.srcs/sources_1/ip/divider2/divider2.xci
set_property is_locked true [get_files C:/Users/adam/Documents/Quantaser_RP_FPGA/kalman_sim/kalman_sim.srcs/sources_1/ip/divider2/divider2.xci]

read_ip -quiet C:/Users/adam/Documents/Quantaser_RP_FPGA/kalman_sim/kalman_sim.srcs/sources_1/ip/multipler/multipler.xci
set_property is_locked true [get_files C:/Users/adam/Documents/Quantaser_RP_FPGA/kalman_sim/kalman_sim.srcs/sources_1/ip/multipler/multipler.xci]

read_ip -quiet C:/Users/adam/Documents/Quantaser_RP_FPGA/kalman_sim/kalman_sim.srcs/sources_1/ip/subtractor/subtractor.xci
set_property is_locked true [get_files C:/Users/adam/Documents/Quantaser_RP_FPGA/kalman_sim/kalman_sim.srcs/sources_1/ip/subtractor/subtractor.xci]

read_ip -quiet C:/Users/adam/Documents/Quantaser_RP_FPGA/kalman_sim/kalman_sim.srcs/sources_1/ip/divider/divider.xci
set_property is_locked true [get_files C:/Users/adam/Documents/Quantaser_RP_FPGA/kalman_sim/kalman_sim.srcs/sources_1/ip/divider/divider.xci]

read_ip -quiet C:/Users/adam/Documents/Quantaser_RP_FPGA/kalman_sim/kalman_sim.srcs/sources_1/ip/adder2/adder2.xci
set_property is_locked true [get_files C:/Users/adam/Documents/Quantaser_RP_FPGA/kalman_sim/kalman_sim.srcs/sources_1/ip/adder2/adder2.xci]

read_ip -quiet C:/Users/adam/Documents/Quantaser_RP_FPGA/kalman_sim/kalman_sim.srcs/sources_1/ip/adder/adder.xci
set_property is_locked true [get_files C:/Users/adam/Documents/Quantaser_RP_FPGA/kalman_sim/kalman_sim.srcs/sources_1/ip/adder/adder.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/adam/Documents/Quantaser_RP_FPGA/kalman_sim/kalman_sim.srcs/constrs_1/new/kal.xdc
set_property used_in_implementation false [get_files C:/Users/adam/Documents/Quantaser_RP_FPGA/kalman_sim/kalman_sim.srcs/constrs_1/new/kal.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top kalman -part xc7z010clg400-1


write_checkpoint -force -noxdef kalman.dcp

catch { report_utilization -file kalman_utilization_synth.rpt -pb kalman_utilization_synth.pb }
